<?php
/** @package Tcc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CertificadoMap.php");

/**
 * CertificadoDAO provides object-oriented access to the certificado table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Tcc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CertificadoDAO extends Phreezable
{
	/** @var int */
	public $IdCertificado;

	/** @var timestamp */
	public $DataEmissao;

	/** @var int */
	public $Livro;

	/** @var int */
	public $Folha;

	/** @var int */
	public $Codigo;

	/** @var int */
	public $IdUsuario;


	/**
	 * Returns a dataset of PalestraPalestrante objects with matching IdCertificado
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdPalestraPalestrantes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "palestra_palestrante_ibfk_3", $criteria);
	}

	/**
	 * Returns a dataset of PalestraParticipante objects with matching IdCertificado
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdPalestraParticipantes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "palestra_participante_ibfk_3", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of IdUsuario
	 * @return Usuario
	 */
	public function GetIdUsuario()
	{
		return $this->_phreezer->GetManyToOne($this, "certificado_ibfk_1");
	}


}
?>