<?php
/** @package Tcc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ModeloCertificadoMap.php");

/**
 * ModeloCertificadoDAO provides object-oriented access to the modelo_certificado table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Tcc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ModeloCertificadoDAO extends Phreezable
{
	/** @var int */
	public $IdModeloCertificado;

	/** @var string */
	public $Nome;

	/** @var string */
	public $TextoParticipante;

	/** @var string */
	public $TextoPalestrante;

	/** @var string */
	public $ArquivoCss;

	/** @var string */
	public $Elementos;


	/**
	 * Returns a dataset of Palestra objects with matching IdModeloCertificado
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdPalestras($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "palestra_ibfk_2", $criteria);
	}


}
?>