<?php
/** @package Tcc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PalestraMap.php");

/**
 * PalestraDAO provides object-oriented access to the palestra table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Tcc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PalestraDAO extends Phreezable
{
	/** @var int */
	public $IdPalestra;

	/** @var string */
	public $Nome;

	/** @var date */
	public $Data;

	/** @var time */
	public $CargaHoraria;

	/** @var int */
	public $ProprioEvento;

	/** @var int */
	public $IdEvento;

	/** @var int */
	public $IdModeloCertificado;


	/**
	 * Returns a dataset of PalestraPalestrante objects with matching IdPalestra
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdPalestraPalestrantes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "palestra_palestrante_ibfk_2", $criteria);
	}

	/**
	 * Returns a dataset of PalestraParticipante objects with matching IdPalestra
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdPalestraParticipantes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "palestra_participante_ibfk_1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of IdModeloCertificado
	 * @return ModeloCertificado
	 */
	public function GetIdModeloCertificado()
	{
		return $this->_phreezer->GetManyToOne($this, "palestra_ibfk_2");
	}

	/**
	 * Returns the foreign object based on the value of IdEvento
	 * @return Evento
	 */
	public function GetIdEvento()
	{
		return $this->_phreezer->GetManyToOne($this, "palestra_ibfk_1");
	}


}
?>