<?php
/** @package Tcc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PalestraParticipanteMap.php");

/**
 * PalestraParticipanteDAO provides object-oriented access to the palestra_participante table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Tcc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PalestraParticipanteDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Presenca;

	/** @var int */
	public $IdParticipante;

	/** @var int */
	public $IdPalestra;

	/** @var int */
	public $IdCertificado;


	/**
	 * Returns the foreign object based on the value of IdPalestra
	 * @return Palestra
	 */
	public function GetIdPalestra()
	{
		return $this->_phreezer->GetManyToOne($this, "palestra_participante_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of IdParticipante
	 * @return Participante
	 */
	public function GetIdParticipante()
	{
		return $this->_phreezer->GetManyToOne($this, "palestra_participante_ibfk_2");
	}

	/**
	 * Returns the foreign object based on the value of IdCertificado
	 * @return Certificado
	 */
	public function GetIdCertificado()
	{
		return $this->_phreezer->GetManyToOne($this, "palestra_participante_ibfk_3");
	}


}
?>