<?php
/** @package Tcc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PalestranteMap.php");

/**
 * PalestranteDAO provides object-oriented access to the palestrante table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Tcc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PalestranteDAO extends Phreezable
{
	/** @var int */
	public $IdPalestrante;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Email;

	/** @var string */
	public $Cpf;

	/** @var string */
	public $Cargo;

	/** @var string */
	public $ImagemAssinatura;


	/**
	 * Returns a dataset of PalestraPalestrante objects with matching IdPalestrante
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdPalestraPalestrantes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "palestra_palestrante_ibfk_1", $criteria);
	}


}
?>