<?php
/** @package Tcc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ParticipanteMap.php");

/**
 * ParticipanteDAO provides object-oriented access to the participante table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Tcc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ParticipanteDAO extends Phreezable
{
	/** @var int */
	public $IdParticipante;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Email;

	/** @var string */
	public $Cpf;


	/**
	 * Returns a dataset of PalestraParticipante objects with matching IdParticipante
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdPalestraParticipantes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "palestra_participante_ibfk_2", $criteria);
	}


}
?>